import type { Metadata } from 'next';
import flowerWedding from '../../public/favicon.svg';
import '../../styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: flowerWedding.src,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode,
}>) {
  return (
    <html lang="en">
      <head>
        {/* Bonus: preload + import font Allura */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Allura&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Playwrite+MX+Guides&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="font-allura bg-brown-medium">{children}</body>
    </html>
  );
}
